# Generated by Django 3.0.2 on 2020-06-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('numble', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numble', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='statistical_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companys', models.CharField(max_length=255)),
                ('numble', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='stockdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MKT_VALUE', models.FloatField()),
                ('NEGOTIABLE_VALUE', models.FloatField()),
                ('AVG_PROFIT_RATE', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='top',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('sum', models.FloatField()),
                ('scale', models.FloatField()),
            ],
        ),
    ]
